package com.bornfire.xbrl.services;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.regex.Pattern;
import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.bornfire.xbrl.dto.ReportControlMasterRowDto;
import com.bornfire.xbrl.dto.ReportControlReportMetaDto;
import com.bornfire.xbrl.dto.ReportControlRunAllResponseDto;
import com.bornfire.xbrl.dto.ReportControlRunStepResponseDto;
import com.bornfire.xbrl.dto.ReportControlStepDto;
import com.bornfire.xbrl.dto.ReportControlStepsResponseDto;
import com.bornfire.xbrl.entities.RT_Report_Master_Entity;
import com.bornfire.xbrl.entities.RT_Report_Master_Repo;
import com.bornfire.xbrl.entities.RT_Report_Step_Entity;
import com.bornfire.xbrl.entities.RT_Report_Step_Exec_Entity;
import com.bornfire.xbrl.entities.RT_Report_Step_Exec_Repo;
import com.bornfire.xbrl.entities.RT_Report_Step_Repo;

@Service
public class ReportControlCenterStepService {

	public static final String ST_SUCCESS = "SUCCESS";
	public static final String ST_FAILED = "FAILED";
	public static final String ST_PENDING = "PENDING";
	public static final String ST_IN_PROGRESS = "IN_PROGRESS";

	private static final Pattern SAFE_PROC = Pattern.compile("^[A-Za-z0-9_.]+$");

	@Autowired
	private RT_Report_Master_Repo masterRepo;

	@Autowired
	private RT_Report_Step_Repo stepRepo;

	@Autowired
	private RT_Report_Step_Exec_Repo stepExecRepo;

	@Autowired
	@Qualifier("srcdataSource")
	private DataSource dataSource;

	@Autowired
	private ReportControlCenterAsyncExecutor asyncExecutor;

	@Transactional(transactionManager = "datasrcTransactionManager", readOnly = true)
	public List<ReportControlStepDto> getStepsForReportAndDay(BigDecimal reportId, Date reportDay) {
		Date day = truncateToDay(reportDay);
		List<RT_Report_Step_Entity> defs = stepRepo.findByReportIdOrdered(reportId);
		List<ReportControlStepDto> out = new ArrayList<>();
		for (RT_Report_Step_Entity def : defs) {
			ReportControlStepDto d = new ReportControlStepDto();
			d.setStepId(def.getStep_id());
			d.setStepOrder(def.getStep_order());
			d.setProcedureName(def.getProcedure_name());
			Optional<RT_Report_Step_Exec_Entity> run = stepExecRepo.findForReportStepAndDay(reportId,
					def.getStep_id(), day);
			if (run.isPresent()) {
				RT_Report_Step_Exec_Entity e = run.get();
				d.setStatus(e.getStatus() != null ? e.getStatus() : ST_PENDING);
				d.setErrorMessage(e.getError_message());
				d.setExecUserName(e.getExec_user_name());
				d.setStepStartTime(e.getStep_start_time());
				d.setStepEndTime(e.getStep_end_time());
			} else {
				d.setStatus(ST_PENDING);
				d.setErrorMessage(null);
				d.setExecUserName(null);
				d.setStepStartTime(null);
				d.setStepEndTime(null);
			}
			out.add(d);
		}
		return out;
	}

	@Transactional(transactionManager = "datasrcTransactionManager", readOnly = true)
	public ReportControlStepsResponseDto getStepsResponseForReportAndDay(BigDecimal reportId, Date reportDay,
			String currentUser) {
		Date day = truncateToDay(reportDay);
		List<ReportControlStepDto> steps = getStepsForReportAndDay(reportId, day);
		ReportControlReportMetaDto meta = buildReportMeta(reportId, day, currentUser, steps);
		return new ReportControlStepsResponseDto(steps, meta);
	}

	@Transactional(transactionManager = "datasrcTransactionManager", readOnly = true)
	public List<ReportControlMasterRowDto> getMasterRowsForDay(Date reportDay) {
		Date day = truncateToDay(reportDay);
		List<RT_Report_Master_Entity> rows = masterRepo.Get_Report_master(day);
		if (rows == null) {
			return new ArrayList<>();
		}
		List<ReportControlMasterRowDto> out = new ArrayList<>();
		for (RT_Report_Master_Entity row : rows) {
			out.add(toMasterRowDto(row, day));
		}
		return out;
	}

	/**
	 * Queues a single step for background execution and returns immediately.
	 */
	@Transactional(transactionManager = "datasrcTransactionManager")
	public ReportControlRunStepResponseDto startStep(BigDecimal reportId, Long stepId, Date reportDay,
			String execUserName) {
		Date day = truncateToDay(reportDay);
		Optional<String> blocker = findBlockingRunner(reportId, day, execUserName);
		if (blocker.isPresent()) {
			return new ReportControlRunStepResponseDto(ST_FAILED,
					"Report is being generated by " + blocker.get() + ". Please wait until it completes.");
		}
		Optional<RT_Report_Master_Entity> mo = masterRepo.findById(reportId);
		if (!mo.isPresent()) {
			return new ReportControlRunStepResponseDto(ST_FAILED, "Report not found");
		}
		RT_Report_Master_Entity master = mo.get();
		if (master.getIs_active() == null || !"Y".equalsIgnoreCase(master.getIs_active().trim())) {
			return new ReportControlRunStepResponseDto(ST_FAILED, "Report is disabled");
		}
		Optional<RT_Report_Step_Entity> so = stepRepo.findById(stepId);
		if (!so.isPresent() || reportId.compareTo(so.get().getReport_id()) != 0) {
			return new ReportControlRunStepResponseDto(ST_FAILED, "Invalid step for this report");
		}

		if (hasAnyStepInProgress(reportId, day)) {
			List<RT_Report_Step_Exec_Entity> runs = stepExecRepo.findByReportAndDay(reportId, day);
			for (RT_Report_Step_Exec_Entity r : runs) {
				if (ST_IN_PROGRESS.equals(r.getStatus()) && !stepId.equals(r.getStep_id())) {
					return new ReportControlRunStepResponseDto(ST_IN_PROGRESS,
							"Another step is already running for this report", true);
				}
			}
		} else if (isReportRunInProgress(reportId, day)) {
			return new ReportControlRunStepResponseDto(ST_IN_PROGRESS,
					"Report generation is in progress — status updates automatically", true);
		}

		RT_Report_Step_Exec_Entity exec = stepExecRepo.findForReportStepAndDay(reportId, stepId, day)
				.orElseGet(() -> newExecRow(reportId, stepId, day));
		if (ST_IN_PROGRESS.equals(exec.getStatus())) {
			return new ReportControlRunStepResponseDto(ST_IN_PROGRESS, "Step is already running", true);
		}

		Date startTs = new Date();
		exec.setExec_user_name(trimToNull(execUserName));
		exec.setStep_start_time(startTs);
		exec.setStep_end_time(null);
		exec.setStatus(ST_IN_PROGRESS);
		exec.setError_message(null);
		stepExecRepo.save(exec);
		master.setReport_status(ST_IN_PROGRESS);
		masterRepo.save(master);

		asyncExecutor.executeStepAsync(reportId, stepId, day, execUserName);
		return new ReportControlRunStepResponseDto(ST_IN_PROGRESS, "Step started — status updates automatically",
				true);
	}

	/**
	 * Runs the Oracle procedure and persists the final step status (invoked asynchronously).
	 */
	@Transactional(transactionManager = "datasrcTransactionManager")
	public void finishStepExecution(BigDecimal reportId, Long stepId, Date reportDay, String execUserName) {
		Date day = truncateToDay(reportDay);
		Optional<RT_Report_Master_Entity> mo = masterRepo.findById(reportId);
		if (!mo.isPresent()) {
			return;
		}
		RT_Report_Master_Entity master = mo.get();
		Optional<RT_Report_Step_Entity> so = stepRepo.findById(stepId);
		if (!so.isPresent() || reportId.compareTo(so.get().getReport_id()) != 0) {
			return;
		}
		RT_Report_Step_Entity step = so.get();

		RT_Report_Step_Exec_Entity exec = stepExecRepo.findForReportStepAndDay(reportId, stepId, day)
				.orElseGet(() -> newExecRow(reportId, stepId, day));
		if (!ST_IN_PROGRESS.equals(exec.getStatus())) {
			exec.setExec_user_name(trimToNull(execUserName));
			exec.setStep_start_time(new Date());
			exec.setStep_end_time(null);
			exec.setStatus(ST_IN_PROGRESS);
			exec.setError_message(null);
		}

		try {
			executeProcedure(step.getProcedure_name(), day);
			exec.setStatus(ST_SUCCESS);
			exec.setError_message(null);
		} catch (Exception e) {
			exec.setStatus(ST_FAILED);
			String msg = e.getMessage() != null ? e.getMessage() : e.getClass().getSimpleName();
			if (msg.length() > 3900) {
				msg = msg.substring(0, 3900);
			}
			exec.setError_message(msg);
		}
		exec.setStep_end_time(new Date());
		stepExecRepo.save(exec);
		refreshMasterAggregates(reportId, day, master);
	}

	/** @deprecated Use {@link #startStep} — kept for any direct callers. */
	@Transactional(transactionManager = "datasrcTransactionManager")
	public ReportControlRunStepResponseDto runStep(BigDecimal reportId, Long stepId, Date reportDay,
			String execUserName) {
		return startStep(reportId, stepId, reportDay, execUserName);
	}

	/**
	 * Queues all steps for background execution and returns immediately.
	 */
	@Transactional(transactionManager = "datasrcTransactionManager")
	public ReportControlRunAllResponseDto startAllSteps(BigDecimal reportId, Date reportDay, String execUserName) {
		Date day = truncateToDay(reportDay);
		List<RT_Report_Step_Entity> steps = stepRepo.findByReportIdOrdered(reportId);
		if (steps == null || steps.isEmpty()) {
			return new ReportControlRunAllResponseDto(ST_FAILED, "No steps configured for this report", 0, 0, null);
		}
		int total = steps.size();
		Optional<String> blocker = findBlockingRunner(reportId, day, execUserName);
		if (blocker.isPresent()) {
			return new ReportControlRunAllResponseDto(ST_FAILED,
					"Report is being generated by " + blocker.get() + ". Please wait until it completes.", 0, total,
					null);
		}
		if (hasAnyStepInProgress(reportId, day) || isReportRunInProgress(reportId, day)) {
			return new ReportControlRunAllResponseDto(ST_IN_PROGRESS,
					"Steps are already running — status updates automatically", 0, total, null);
		}
		Optional<RT_Report_Master_Entity> mo = masterRepo.findById(reportId);
		if (mo.isPresent()) {
			RT_Report_Master_Entity master = mo.get();
			master.setReport_status(ST_IN_PROGRESS);
			masterRepo.save(master);
		}
		// Mark first step in-progress synchronously so UI shows "Running" immediately.
		markStepInProgress(reportId, steps.get(0).getStep_id(), day, execUserName);
		asyncExecutor.executeAllStepsAsync(reportId, day, execUserName);
		return new ReportControlRunAllResponseDto(ST_IN_PROGRESS,
				"All steps started — each step will update as it completes", 0, total, null);
	}

	/**
	 * Runs all steps in order on a background thread. Stops at the first failure.
	 */
	public void runAllStepsBlocking(BigDecimal reportId, Date reportDay, String execUserName) {
		Date day = truncateToDay(reportDay);
		List<RT_Report_Step_Entity> steps = stepRepo.findByReportIdOrdered(reportId);
		if (steps == null || steps.isEmpty()) {
			return;
		}
		for (RT_Report_Step_Entity s : steps) {
			markStepInProgress(reportId, s.getStep_id(), day, execUserName);
			finishStepExecution(reportId, s.getStep_id(), day, execUserName);
			Optional<RT_Report_Step_Exec_Entity> exec = stepExecRepo.findForReportStepAndDay(reportId, s.getStep_id(),
					day);
			if (exec.isPresent() && ST_FAILED.equals(exec.get().getStatus())) {
				break;
			}
		}
	}

	/** @deprecated Use {@link #startAllSteps}. */
	@Transactional(transactionManager = "datasrcTransactionManager")
	public ReportControlRunAllResponseDto runAllSteps(BigDecimal reportId, Date reportDay, String execUserName) {
		return startAllSteps(reportId, reportDay, execUserName);
	}

	@Transactional(transactionManager = "datasrcTransactionManager")
	public void markStepInProgress(BigDecimal reportId, Long stepId, Date day, String execUserName) {
		RT_Report_Step_Exec_Entity exec = stepExecRepo.findForReportStepAndDay(reportId, stepId, day)
				.orElseGet(() -> newExecRow(reportId, stepId, day));
		exec.setExec_user_name(trimToNull(execUserName));
		exec.setStep_start_time(new Date());
		exec.setStep_end_time(null);
		exec.setStatus(ST_IN_PROGRESS);
		exec.setError_message(null);
		stepExecRepo.save(exec);
	}

	private boolean hasAnyStepInProgress(BigDecimal reportId, Date day) {
		List<RT_Report_Step_Exec_Entity> runs = stepExecRepo.findByReportAndDay(reportId, day);
		for (RT_Report_Step_Exec_Entity r : runs) {
			if (ST_IN_PROGRESS.equals(r.getStatus())) {
				return true;
			}
		}
		return false;
	}

	private boolean isRunInProgressFromSteps(List<ReportControlStepDto> steps, BigDecimal reportId, Date day) {
		if (steps == null || steps.isEmpty()) {
			return isReportRunInProgress(reportId, day);
		}
		for (ReportControlStepDto s : steps) {
			if (ST_IN_PROGRESS.equals(s.getStatus())) {
				return true;
			}
		}
		int total = steps.size();
		int ok = 0;
		int fail = 0;
		for (ReportControlStepDto s : steps) {
			if (ST_SUCCESS.equals(s.getStatus())) {
				ok++;
			} else if (ST_FAILED.equals(s.getStatus())) {
				fail++;
			}
		}
		if (fail > 0 || ok >= total) {
			return false;
		}
		if (ok > 0) {
			return true;
		}
		return false;
	}

	private boolean isReportRunInProgress(BigDecimal reportId, Date day) {
		if (hasAnyStepInProgress(reportId, day)) {
			return true;
		}
		Optional<RT_Report_Master_Entity> mo = masterRepo.findById(reportId);
		if (!mo.isPresent()) {
			return false;
		}
		if (!ST_IN_PROGRESS.equals(mo.get().getReport_status())) {
			return false;
		}
		int total = stepRepo.findByReportIdOrdered(reportId).size();
		if (total <= 0) {
			return false;
		}
		List<RT_Report_Step_Exec_Entity> runs = stepExecRepo.findByReportAndDay(reportId, day);
		int ok = 0;
		int fail = 0;
		for (RT_Report_Step_Exec_Entity r : runs) {
			if (ST_SUCCESS.equals(r.getStatus())) {
				ok++;
			} else if (ST_FAILED.equals(r.getStatus())) {
				fail++;
			}
		}
		return ok < total && fail == 0;
	}

	private Optional<String> resolveActiveRunner(BigDecimal reportId, Date day) {
		List<RT_Report_Step_Exec_Entity> runs = stepExecRepo.findByReportAndDay(reportId, day);
		for (RT_Report_Step_Exec_Entity r : runs) {
			if (ST_IN_PROGRESS.equals(r.getStatus())) {
				String u = trimToNull(r.getExec_user_name());
				if (u != null) {
					return Optional.of(u);
				}
			}
		}
		if (!isReportRunInProgress(reportId, day)) {
			return Optional.empty();
		}
		return runs.stream().filter(r -> trimToNull(r.getExec_user_name()) != null && r.getStep_start_time() != null)
				.max(Comparator.comparing(RT_Report_Step_Exec_Entity::getStep_start_time))
				.map(r -> trimToNull(r.getExec_user_name()));
	}

	private Optional<String> findBlockingRunner(BigDecimal reportId, Date day, String currentUser) {
		Optional<String> runner = resolveActiveRunner(reportId, day);
		String cur = trimToNull(currentUser);
		if (!runner.isPresent() || cur == null) {
			return Optional.empty();
		}
		if (!runner.get().equalsIgnoreCase(cur)) {
			return runner;
		}
		return Optional.empty();
	}

	private ReportControlReportMetaDto buildReportMeta(BigDecimal reportId, Date day, String currentUser,
			List<ReportControlStepDto> steps) {
		ReportControlReportMetaDto meta = new ReportControlReportMetaDto();
		Optional<RT_Report_Master_Entity> mo = masterRepo.findById(reportId);
		if (mo.isPresent()) {
			RT_Report_Master_Entity m = mo.get();
			meta.setReportStatus(m.getReport_status());
			meta.setTotalSteps(m.getTotal_steps());
			meta.setCompletedSteps(m.getCompleted_steps());
			meta.setFailedSteps(m.getFailed_steps());
			meta.setReportDate(m.getReport_date());
		}
		if (steps != null && !steps.isEmpty()) {
			meta.setTotalSteps(steps.size());
			int ok = 0;
			int fail = 0;
			for (ReportControlStepDto s : steps) {
				if (ST_SUCCESS.equals(s.getStatus())) {
					ok++;
				} else if (ST_FAILED.equals(s.getStatus())) {
					fail++;
				}
			}
			meta.setCompletedSteps(ok);
			meta.setFailedSteps(fail);
			if (ok >= steps.size() && fail == 0) {
				meta.setReportStatus(ST_SUCCESS);
			} else if (fail > 0) {
				meta.setReportStatus(ST_FAILED);
			}
		}
		boolean runInProgress = isRunInProgressFromSteps(steps, reportId, day);
		if (steps != null && !steps.isEmpty()) {
			int ok = 0;
			for (ReportControlStepDto s : steps) {
				if (ST_SUCCESS.equals(s.getStatus())) {
					ok++;
				}
			}
			if (ok >= steps.size()) {
				runInProgress = false;
				meta.setReportStatus(ST_SUCCESS);
			}
		}
		meta.setRunInProgress(runInProgress);
		Optional<String> runner = resolveActiveRunner(reportId, day);
		runner.ifPresent(meta::setActiveRunner);
		Optional<String> blocker = findBlockingRunner(reportId, day, currentUser);
		if (blocker.isPresent()) {
			meta.setLockedByOtherUser(true);
			meta.setLockMessage("Report is being generated by " + blocker.get() + ". Please wait.");
		} else {
			meta.setLockedByOtherUser(false);
			meta.setLockMessage(null);
		}
		return meta;
	}

	private ReportControlMasterRowDto toMasterRowDto(RT_Report_Master_Entity row, Date selectedDay) {
		ReportControlMasterRowDto d = new ReportControlMasterRowDto();
		d.setReportId(row.getReport_id());
		d.setReportName(row.getReport_name());
		d.setReportStatus(row.getReport_status());
		d.setTotalSteps(row.getTotal_steps());
		d.setCompletedSteps(row.getCompleted_steps());
		d.setFailedSteps(row.getFailed_steps());
		d.setReportDate(row.getReport_date());
		boolean gen = row.getReport_date() != null && truncateToDay(row.getReport_date()).equals(selectedDay);
		d.setGeneratedForSelectedDay(gen);
		String rs = row.getReport_status() != null ? row.getReport_status().trim() : "";
		d.setRunInProgress(ST_IN_PROGRESS.equalsIgnoreCase(rs));
		return d;
	}

	private RT_Report_Step_Exec_Entity newExecRow(BigDecimal reportId, Long stepId, Date day) {
		RT_Report_Step_Exec_Entity e = new RT_Report_Step_Exec_Entity();
		e.setReport_id(reportId);
		e.setStep_id(stepId);
		e.setReport_date(day);
		e.setStatus(ST_PENDING);
		return e;
	}

	private void refreshMasterAggregates(BigDecimal reportId, Date day, RT_Report_Master_Entity master) {
		int total = stepRepo.findByReportIdOrdered(reportId).size();
		List<RT_Report_Step_Exec_Entity> runs = stepExecRepo.findByReportAndDay(reportId, day);
		int ok = 0;
		int fail = 0;
		for (RT_Report_Step_Exec_Entity r : runs) {
			if (ST_SUCCESS.equals(r.getStatus())) {
				ok++;
			} else if (ST_FAILED.equals(r.getStatus())) {
				fail++;
			}
		}
		master.setTotal_steps(total);
		master.setCompleted_steps(ok);
		master.setFailed_steps(fail);
		if (total <= 0) {
			master.setReport_status(ST_PENDING);
		} else if (fail > 0) {
			master.setReport_status(ST_FAILED);
		} else if (ok >= total) {
			master.setReport_status(ST_SUCCESS);
		} else {
			master.setReport_status(ST_IN_PROGRESS);
		}
		masterRepo.save(master);
	}

	public void executeProcedure(String procedureName, Date reportDay) throws Exception {
		if (procedureName == null || !SAFE_PROC.matcher(procedureName.trim()).matches()) {
			throw new IllegalArgumentException("Invalid procedure name");
		}
		String name = procedureName.trim();
		String dateStr = formatReportDateForProcedure(reportDay);
		try (Connection conn = dataSource.getConnection();
				CallableStatement stmt = conn.prepareCall("{ call " + name + "(?) }")) {
			stmt.setString(1, dateStr);
			stmt.execute();
		}
	}

	/**
	 * Formats the calendar day as {@code 31-DEC-2025} for passing to Oracle procedures.
	 */
	public static String formatReportDateForProcedure(Date reportDay) {
		Date day = reportDay == null ? new Date() : reportDay;
		Calendar c = Calendar.getInstance();
		c.setTime(day);
		c.set(Calendar.HOUR_OF_DAY, 0);
		c.set(Calendar.MINUTE, 0);
		c.set(Calendar.SECOND, 0);
		c.set(Calendar.MILLISECOND, 0);
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH);
		String s = sdf.format(c.getTime());
		String[] p = s.split("-");
		if (p.length == 3) {
			return p[0] + "-" + p[1].toUpperCase(Locale.ENGLISH) + "-" + p[2];
		}
		return s.toUpperCase(Locale.ENGLISH);
	}

	private static Date truncateToDay(Date d) {
		Calendar c = Calendar.getInstance();
		c.setTime(d);
		c.set(Calendar.HOUR_OF_DAY, 0);
		c.set(Calendar.MINUTE, 0);
		c.set(Calendar.SECOND, 0);
		c.set(Calendar.MILLISECOND, 0);
		return c.getTime();
	}

	private static String trimToNull(String s) {
		if (s == null) {
			return null;
		}
		String t = s.trim();
		return t.isEmpty() ? null : t;
	}
}
