package com.bornfire.xbrl.entities;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

@Entity
@IdClass(RT_EAR_IDCLASS.class)
@Table(name = "RT_EAR_TABLE")
public class RT_EAR_ENTITY {

	@Id
	private Date REPORT_DATE;
	private Date LAST_YEAR_END_DATE;
	private BigDecimal AED_TO_INR_CONV_RATE;
	private BigDecimal INT_EARNED_YEAR_END_AMT_IN_AED_THOUSAND;
	private BigDecimal INT_PAID_YEAR_END_AMT_IN_AED_THOUSAND;
	private BigDecimal INT_EARNED_YEAR_END_AMT_IN_INR_THOUSAND;
	private BigDecimal INT_PAID_YEAR_END_AMT_IN_INR_THOUSAND;
	private BigDecimal REPRICING_ASSETS_ONE_28_DAYS;
	private BigDecimal REPRICING_ASSETS_29_TO_3MON;
	private BigDecimal REPRICING_ASSETS_3MON_TO_6MON;
	private BigDecimal REPRICING_ASSETS_6MON_1YEAR;
	private BigDecimal REPRICABLE_ASSETS_ONE_28_DAYS;
	private BigDecimal REPRICABLE_ASSETS_29_TO_3MON;
	private BigDecimal REPRICABLE_ASSETS_3MON_TO_6MON;
	private BigDecimal REPRICABLE_ASSETS_6MON_1YEAR;
	private BigDecimal TOTAL_ASST_REPRICING_AMT_IN_AED_THOUSAND;
	private BigDecimal TOTAL_ASST_REPRICABLE_AMT_IN_AED_THOUSAND;
	private BigDecimal NET_ASST_PRODUCT_AMT_IN_AED;
	private BigDecimal REPRICING_LIAB_ONE_28_DAYS;
	private BigDecimal REPRICING_LIAB_29_TO_3MON;
	private BigDecimal REPRICING_LIAB_3MON_TO_6MON;
	private BigDecimal REPRICING_LIAB_6MON_1YEAR;
	private BigDecimal REPRICABLE_LIAB_ONE_28_DAYS;
	private BigDecimal REPRICABLE_LIAB_29_TO_3MON;
	private BigDecimal REPRICABLE_LIAB_3MON_TO_6MON;
	private BigDecimal REPRICABLE_LIAB_6MON_1YEAR;
	private BigDecimal TOTAL_LIAB_REPRICING_AMT_IN_AED_THOUSAND;
	private BigDecimal TOTAL_LIAB_REPRICABLE_AMT_IN_AED_THOUSAND;
	private BigDecimal NET_LIAB_PRODUCT_AMT_IN_AED;
	private BigDecimal LAST_YEAR_NII_AMT_IN_AED;
	private BigDecimal LAST_YEAR_NII_AMT_IN_INR_CRORE;
	private BigDecimal LAST_4_QUARTER_AMT_IN_AED;
	private BigDecimal LAST_4_QUARTER_AMT_IN_INR_CRORE;
	private BigDecimal EAR_TOLERANCE_LIMIT_AMT_IN_AED;
	private BigDecimal EAR_AMT_IN_AED;
	private BigDecimal EAR_TOLERANCE_LIMIT_AMT_IN_INR_CRORE;
	private BigDecimal EAR_AMT_IN_INR_CRORE;
	@Id
	private String REPORT_TYPE;
	private Date START_DATE_LAST_4;
	private Date END_DATE_LAST_4;

	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}

	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}

	public Date getLAST_YEAR_END_DATE() {
		return LAST_YEAR_END_DATE;
	}

	public void setLAST_YEAR_END_DATE(Date lAST_YEAR_END_DATE) {
		LAST_YEAR_END_DATE = lAST_YEAR_END_DATE;
	}

	public BigDecimal getAED_TO_INR_CONV_RATE() {
		return AED_TO_INR_CONV_RATE;
	}

	public void setAED_TO_INR_CONV_RATE(BigDecimal aED_TO_INR_CONV_RATE) {
		AED_TO_INR_CONV_RATE = aED_TO_INR_CONV_RATE;
	}

	public BigDecimal getINT_EARNED_YEAR_END_AMT_IN_AED_THOUSAND() {
		return INT_EARNED_YEAR_END_AMT_IN_AED_THOUSAND;
	}

	public void setINT_EARNED_YEAR_END_AMT_IN_AED_THOUSAND(BigDecimal iNT_EARNED_YEAR_END_AMT_IN_AED_THOUSAND) {
		INT_EARNED_YEAR_END_AMT_IN_AED_THOUSAND = iNT_EARNED_YEAR_END_AMT_IN_AED_THOUSAND;
	}

	public BigDecimal getINT_PAID_YEAR_END_AMT_IN_AED_THOUSAND() {
		return INT_PAID_YEAR_END_AMT_IN_AED_THOUSAND;
	}

	public void setINT_PAID_YEAR_END_AMT_IN_AED_THOUSAND(BigDecimal iNT_PAID_YEAR_END_AMT_IN_AED_THOUSAND) {
		INT_PAID_YEAR_END_AMT_IN_AED_THOUSAND = iNT_PAID_YEAR_END_AMT_IN_AED_THOUSAND;
	}

	public BigDecimal getINT_EARNED_YEAR_END_AMT_IN_INR_THOUSAND() {
		return INT_EARNED_YEAR_END_AMT_IN_INR_THOUSAND;
	}

	public void setINT_EARNED_YEAR_END_AMT_IN_INR_THOUSAND(BigDecimal iNT_EARNED_YEAR_END_AMT_IN_INR_THOUSAND) {
		INT_EARNED_YEAR_END_AMT_IN_INR_THOUSAND = iNT_EARNED_YEAR_END_AMT_IN_INR_THOUSAND;
	}

	public BigDecimal getINT_PAID_YEAR_END_AMT_IN_INR_THOUSAND() {
		return INT_PAID_YEAR_END_AMT_IN_INR_THOUSAND;
	}

	public void setINT_PAID_YEAR_END_AMT_IN_INR_THOUSAND(BigDecimal iNT_PAID_YEAR_END_AMT_IN_INR_THOUSAND) {
		INT_PAID_YEAR_END_AMT_IN_INR_THOUSAND = iNT_PAID_YEAR_END_AMT_IN_INR_THOUSAND;
	}

	public BigDecimal getREPRICING_ASSETS_ONE_28_DAYS() {
		return REPRICING_ASSETS_ONE_28_DAYS;
	}

	public void setREPRICING_ASSETS_ONE_28_DAYS(BigDecimal rEPRICING_ASSETS_ONE_28_DAYS) {
		REPRICING_ASSETS_ONE_28_DAYS = rEPRICING_ASSETS_ONE_28_DAYS;
	}

	public BigDecimal getREPRICING_ASSETS_29_TO_3MON() {
		return REPRICING_ASSETS_29_TO_3MON;
	}

	public void setREPRICING_ASSETS_29_TO_3MON(BigDecimal rEPRICING_ASSETS_29_TO_3MON) {
		REPRICING_ASSETS_29_TO_3MON = rEPRICING_ASSETS_29_TO_3MON;
	}

	public BigDecimal getREPRICING_ASSETS_3MON_TO_6MON() {
		return REPRICING_ASSETS_3MON_TO_6MON;
	}

	public void setREPRICING_ASSETS_3MON_TO_6MON(BigDecimal rEPRICING_ASSETS_3MON_TO_6MON) {
		REPRICING_ASSETS_3MON_TO_6MON = rEPRICING_ASSETS_3MON_TO_6MON;
	}

	public BigDecimal getREPRICING_ASSETS_6MON_1YEAR() {
		return REPRICING_ASSETS_6MON_1YEAR;
	}

	public void setREPRICING_ASSETS_6MON_1YEAR(BigDecimal rEPRICING_ASSETS_6MON_1YEAR) {
		REPRICING_ASSETS_6MON_1YEAR = rEPRICING_ASSETS_6MON_1YEAR;
	}

	public BigDecimal getREPRICABLE_ASSETS_ONE_28_DAYS() {
		return REPRICABLE_ASSETS_ONE_28_DAYS;
	}

	public void setREPRICABLE_ASSETS_ONE_28_DAYS(BigDecimal rEPRICABLE_ASSETS_ONE_28_DAYS) {
		REPRICABLE_ASSETS_ONE_28_DAYS = rEPRICABLE_ASSETS_ONE_28_DAYS;
	}

	public BigDecimal getREPRICABLE_ASSETS_29_TO_3MON() {
		return REPRICABLE_ASSETS_29_TO_3MON;
	}

	public void setREPRICABLE_ASSETS_29_TO_3MON(BigDecimal rEPRICABLE_ASSETS_29_TO_3MON) {
		REPRICABLE_ASSETS_29_TO_3MON = rEPRICABLE_ASSETS_29_TO_3MON;
	}

	public BigDecimal getREPRICABLE_ASSETS_3MON_TO_6MON() {
		return REPRICABLE_ASSETS_3MON_TO_6MON;
	}

	public void setREPRICABLE_ASSETS_3MON_TO_6MON(BigDecimal rEPRICABLE_ASSETS_3MON_TO_6MON) {
		REPRICABLE_ASSETS_3MON_TO_6MON = rEPRICABLE_ASSETS_3MON_TO_6MON;
	}

	public BigDecimal getREPRICABLE_ASSETS_6MON_1YEAR() {
		return REPRICABLE_ASSETS_6MON_1YEAR;
	}

	public void setREPRICABLE_ASSETS_6MON_1YEAR(BigDecimal rEPRICABLE_ASSETS_6MON_1YEAR) {
		REPRICABLE_ASSETS_6MON_1YEAR = rEPRICABLE_ASSETS_6MON_1YEAR;
	}

	public BigDecimal getTOTAL_ASST_REPRICING_AMT_IN_AED_THOUSAND() {
		return TOTAL_ASST_REPRICING_AMT_IN_AED_THOUSAND;
	}

	public void setTOTAL_ASST_REPRICING_AMT_IN_AED_THOUSAND(BigDecimal tOTAL_ASST_REPRICING_AMT_IN_AED_THOUSAND) {
		TOTAL_ASST_REPRICING_AMT_IN_AED_THOUSAND = tOTAL_ASST_REPRICING_AMT_IN_AED_THOUSAND;
	}

	public BigDecimal getTOTAL_ASST_REPRICABLE_AMT_IN_AED_THOUSAND() {
		return TOTAL_ASST_REPRICABLE_AMT_IN_AED_THOUSAND;
	}

	public void setTOTAL_ASST_REPRICABLE_AMT_IN_AED_THOUSAND(BigDecimal tOTAL_ASST_REPRICABLE_AMT_IN_AED_THOUSAND) {
		TOTAL_ASST_REPRICABLE_AMT_IN_AED_THOUSAND = tOTAL_ASST_REPRICABLE_AMT_IN_AED_THOUSAND;
	}

	public BigDecimal getNET_ASST_PRODUCT_AMT_IN_AED() {
		return NET_ASST_PRODUCT_AMT_IN_AED;
	}

	public void setNET_ASST_PRODUCT_AMT_IN_AED(BigDecimal nET_ASST_PRODUCT_AMT_IN_AED) {
		NET_ASST_PRODUCT_AMT_IN_AED = nET_ASST_PRODUCT_AMT_IN_AED;
	}

	public BigDecimal getREPRICING_LIAB_ONE_28_DAYS() {
		return REPRICING_LIAB_ONE_28_DAYS;
	}

	public void setREPRICING_LIAB_ONE_28_DAYS(BigDecimal rEPRICING_LIAB_ONE_28_DAYS) {
		REPRICING_LIAB_ONE_28_DAYS = rEPRICING_LIAB_ONE_28_DAYS;
	}

	public BigDecimal getREPRICING_LIAB_29_TO_3MON() {
		return REPRICING_LIAB_29_TO_3MON;
	}

	public void setREPRICING_LIAB_29_TO_3MON(BigDecimal rEPRICING_LIAB_29_TO_3MON) {
		REPRICING_LIAB_29_TO_3MON = rEPRICING_LIAB_29_TO_3MON;
	}

	public BigDecimal getREPRICING_LIAB_3MON_TO_6MON() {
		return REPRICING_LIAB_3MON_TO_6MON;
	}

	public void setREPRICING_LIAB_3MON_TO_6MON(BigDecimal rEPRICING_LIAB_3MON_TO_6MON) {
		REPRICING_LIAB_3MON_TO_6MON = rEPRICING_LIAB_3MON_TO_6MON;
	}

	public BigDecimal getREPRICING_LIAB_6MON_1YEAR() {
		return REPRICING_LIAB_6MON_1YEAR;
	}

	public void setREPRICING_LIAB_6MON_1YEAR(BigDecimal rEPRICING_LIAB_6MON_1YEAR) {
		REPRICING_LIAB_6MON_1YEAR = rEPRICING_LIAB_6MON_1YEAR;
	}

	public BigDecimal getREPRICABLE_LIAB_ONE_28_DAYS() {
		return REPRICABLE_LIAB_ONE_28_DAYS;
	}

	public void setREPRICABLE_LIAB_ONE_28_DAYS(BigDecimal rEPRICABLE_LIAB_ONE_28_DAYS) {
		REPRICABLE_LIAB_ONE_28_DAYS = rEPRICABLE_LIAB_ONE_28_DAYS;
	}

	public BigDecimal getREPRICABLE_LIAB_29_TO_3MON() {
		return REPRICABLE_LIAB_29_TO_3MON;
	}

	public void setREPRICABLE_LIAB_29_TO_3MON(BigDecimal rEPRICABLE_LIAB_29_TO_3MON) {
		REPRICABLE_LIAB_29_TO_3MON = rEPRICABLE_LIAB_29_TO_3MON;
	}

	public BigDecimal getREPRICABLE_LIAB_3MON_TO_6MON() {
		return REPRICABLE_LIAB_3MON_TO_6MON;
	}

	public void setREPRICABLE_LIAB_3MON_TO_6MON(BigDecimal rEPRICABLE_LIAB_3MON_TO_6MON) {
		REPRICABLE_LIAB_3MON_TO_6MON = rEPRICABLE_LIAB_3MON_TO_6MON;
	}

	public BigDecimal getREPRICABLE_LIAB_6MON_1YEAR() {
		return REPRICABLE_LIAB_6MON_1YEAR;
	}

	public void setREPRICABLE_LIAB_6MON_1YEAR(BigDecimal rEPRICABLE_LIAB_6MON_1YEAR) {
		REPRICABLE_LIAB_6MON_1YEAR = rEPRICABLE_LIAB_6MON_1YEAR;
	}

	public BigDecimal getTOTAL_LIAB_REPRICING_AMT_IN_AED_THOUSAND() {
		return TOTAL_LIAB_REPRICING_AMT_IN_AED_THOUSAND;
	}

	public void setTOTAL_LIAB_REPRICING_AMT_IN_AED_THOUSAND(BigDecimal tOTAL_LIAB_REPRICING_AMT_IN_AED_THOUSAND) {
		TOTAL_LIAB_REPRICING_AMT_IN_AED_THOUSAND = tOTAL_LIAB_REPRICING_AMT_IN_AED_THOUSAND;
	}

	public BigDecimal getTOTAL_LIAB_REPRICABLE_AMT_IN_AED_THOUSAND() {
		return TOTAL_LIAB_REPRICABLE_AMT_IN_AED_THOUSAND;
	}

	public void setTOTAL_LIAB_REPRICABLE_AMT_IN_AED_THOUSAND(BigDecimal tOTAL_LIAB_REPRICABLE_AMT_IN_AED_THOUSAND) {
		TOTAL_LIAB_REPRICABLE_AMT_IN_AED_THOUSAND = tOTAL_LIAB_REPRICABLE_AMT_IN_AED_THOUSAND;
	}

	public BigDecimal getNET_LIAB_PRODUCT_AMT_IN_AED() {
		return NET_LIAB_PRODUCT_AMT_IN_AED;
	}

	public void setNET_LIAB_PRODUCT_AMT_IN_AED(BigDecimal nET_LIAB_PRODUCT_AMT_IN_AED) {
		NET_LIAB_PRODUCT_AMT_IN_AED = nET_LIAB_PRODUCT_AMT_IN_AED;
	}

	public BigDecimal getLAST_YEAR_NII_AMT_IN_AED() {
		return LAST_YEAR_NII_AMT_IN_AED;
	}

	public void setLAST_YEAR_NII_AMT_IN_AED(BigDecimal lAST_YEAR_NII_AMT_IN_AED) {
		LAST_YEAR_NII_AMT_IN_AED = lAST_YEAR_NII_AMT_IN_AED;
	}

	public BigDecimal getLAST_YEAR_NII_AMT_IN_INR_CRORE() {
		return LAST_YEAR_NII_AMT_IN_INR_CRORE;
	}

	public void setLAST_YEAR_NII_AMT_IN_INR_CRORE(BigDecimal lAST_YEAR_NII_AMT_IN_INR_CRORE) {
		LAST_YEAR_NII_AMT_IN_INR_CRORE = lAST_YEAR_NII_AMT_IN_INR_CRORE;
	}

	public BigDecimal getLAST_4_QUARTER_AMT_IN_AED() {
		return LAST_4_QUARTER_AMT_IN_AED;
	}

	public void setLAST_4_QUARTER_AMT_IN_AED(BigDecimal lAST_4_QUARTER_AMT_IN_AED) {
		LAST_4_QUARTER_AMT_IN_AED = lAST_4_QUARTER_AMT_IN_AED;
	}

	public BigDecimal getLAST_4_QUARTER_AMT_IN_INR_CRORE() {
		return LAST_4_QUARTER_AMT_IN_INR_CRORE;
	}

	public void setLAST_4_QUARTER_AMT_IN_INR_CRORE(BigDecimal lAST_4_QUARTER_AMT_IN_INR_CRORE) {
		LAST_4_QUARTER_AMT_IN_INR_CRORE = lAST_4_QUARTER_AMT_IN_INR_CRORE;
	}

	public BigDecimal getEAR_TOLERANCE_LIMIT_AMT_IN_AED() {
		return EAR_TOLERANCE_LIMIT_AMT_IN_AED;
	}

	public void setEAR_TOLERANCE_LIMIT_AMT_IN_AED(BigDecimal eAR_TOLERANCE_LIMIT_AMT_IN_AED) {
		EAR_TOLERANCE_LIMIT_AMT_IN_AED = eAR_TOLERANCE_LIMIT_AMT_IN_AED;
	}

	public BigDecimal getEAR_AMT_IN_AED() {
		return EAR_AMT_IN_AED;
	}

	public void setEAR_AMT_IN_AED(BigDecimal eAR_AMT_IN_AED) {
		EAR_AMT_IN_AED = eAR_AMT_IN_AED;
	}

	public BigDecimal getEAR_TOLERANCE_LIMIT_AMT_IN_INR_CRORE() {
		return EAR_TOLERANCE_LIMIT_AMT_IN_INR_CRORE;
	}

	public void setEAR_TOLERANCE_LIMIT_AMT_IN_INR_CRORE(BigDecimal eAR_TOLERANCE_LIMIT_AMT_IN_INR_CRORE) {
		EAR_TOLERANCE_LIMIT_AMT_IN_INR_CRORE = eAR_TOLERANCE_LIMIT_AMT_IN_INR_CRORE;
	}

	public BigDecimal getEAR_AMT_IN_INR_CRORE() {
		return EAR_AMT_IN_INR_CRORE;
	}

	public void setEAR_AMT_IN_INR_CRORE(BigDecimal eAR_AMT_IN_INR_CRORE) {
		EAR_AMT_IN_INR_CRORE = eAR_AMT_IN_INR_CRORE;
	}

	public String getREPORT_TYPE() {
		return REPORT_TYPE;
	}

	public void setREPORT_TYPE(String rEPORT_TYPE) {
		REPORT_TYPE = rEPORT_TYPE;
	}

	public Date getSTART_DATE_LAST_4() {
		return START_DATE_LAST_4;
	}

	public void setSTART_DATE_LAST_4(Date sTART_DATE_LAST_4) {
		START_DATE_LAST_4 = sTART_DATE_LAST_4;
	}

	public Date getEND_DATE_LAST_4() {
		return END_DATE_LAST_4;
	}

	public void setEND_DATE_LAST_4(Date eND_DATE_LAST_4) {
		END_DATE_LAST_4 = eND_DATE_LAST_4;
	}

}
