package com.bornfire.xbrl.entities;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import oracle.sql.DATE;

public interface RT_SLS_Repository extends JpaRepository<RT_SLS_ENTITIES, String> {
	 
	@Query(value = "select * from RT_SLS_USD order by REPORT_DATE", nativeQuery = true)
	 List<RT_SLS_ENTITIES> rtslslist();
	 
	 @Query(value = "select * from RT_SLS_USD where REPORT_DATE=?1 AND REPORT_CURRENCY=?2 ", nativeQuery = true)
	 List<RT_SLS_ENTITIES> rtslslistbydate(Date reportdate,String currency);
	 
	 @Query(value = "select * from RT_SLS_USD where REPORT_DATE=?1", nativeQuery = true)
	 List<RT_SLS_ENTITIES> rtslslistonlydate(Date reportdate);
	 
	 @Query(value = "SELECT VOLATILE_LIAB_UPTO_1_YR_TOTAL,TEMPORART_ASSETS_TOTAL,EARNING_ASSETS_TOTAL,CASA_ABV_1_YR_TOTAL,TOTAL_ASSETS,\r\n"
	 		+ "Loans_Mandatory_SLR_Mandatory_CRR_Fixed_assets,VOLATILE_LIAB_TEMP_ASSETS_DIVIDED_EARNING_ASSETS_TEMP_ASSETS,\r\n"
	 		+ "CORE_DEPOSIT_DIVIDED_TOTAL_ASSETS, ADV_CRR_FIXED_ASSET_DIVI_TOTAL_ASSET, ADV_CRR_FIXED_ASSET_DIVI_CORE_DEPO,\r\n"
	 		+ "TEMPORARY_ASSETS_DIVIDED_TOTAL_ASSETS, TEMPORARY_ASSETS_DIVIDED_VOLATILE_LIAB, VOLATILE_LIAB_DIVIDED_TOTAL_ASSETS from(\r\n"
	 		+ "SELECT CASH, BALANCE_WITH_BANKS, BP_BD_UPTO_1_YEAR, INVEST_UPTO_1_YEAR, SWAP_FUND_UPTO_1_YEAR_ASSET,\r\n"
	 		+ "TEMPORART_ASSETS_TOTAL,(TEMPORART_ASSETS_TOTAL - SWAP_FUND_UPTO_1_YEAR_ASSET) AS STOCK_TEMPORART_ASSETS_TOTAL_WITHOUT_SWAP\r\n"
	 		+ ", CRR, BALANCE_CURRENT_ACC_OTHER_BANKS, OTHER_ASSETS, EARNING_ASSETS_TOTAL,\r\n"
	 		+ "TOTAL_ASSETS, NET_OF_EARNING_ASSETS_TOTAL, INTERBANK, CASA, TERM_DEPOSIT, NETWORTH, CASA_ABV_1_YR_TOTAL,\r\n"
	 		+ "TD_UPTO_1_YEAR, DEPOSIT_INTERBANK_CASA, BORROWINGS, LC_FULL, SWAP_FUND_UPTO_1_YEAR_LIAB, VOLATILE_LIAB_UPTO_1_YR_TOTAL,\r\n"
	 		+ "(VOLATILE_LIAB_UPTO_1_YR_TOTAL-SWAP_FUND_UPTO_1_YEAR_LIAB) STOCK_VOLATILE_LIAB_TOTAL_WITHOUT_SWAP,\r\n"
	 		+ "Round(((VOLATILE_LIAB_UPTO_1_YR_TOTAL - TEMPORART_ASSETS_TOTAL)/\r\n"
	 		+ "(NET_OF_EARNING_ASSETS_TOTAL - TEMPORART_ASSETS_TOTAL))*100,2) AS Volatile_Liab_Temp_Assets_divided_Earning_Assets_Temp_Assets,\r\n"
	 		+ "Round((CASA_ABV_1_YR_TOTAL/TOTAL_ASSETS)*100,2) As Core_Deposit_divided_Total_Assets,\r\n"
	 		+ "Round(((TOTAL_ADVANCES+ FIXED_ASSETS+CRR)/TOTAL_ASSETS)*100,2) As Adv_CRR_Fixed_asset_divi_Total_asset,\r\n"
	 		+ "Round(((TOTAL_ADVANCES+ FIXED_ASSETS+CRR)/CASA_ABV_1_YR_TOTAL)*100,2) As Adv_CRR_Fixed_asset_divi_Core_Depo,\r\n"
	 		+ "Round((TEMPORART_ASSETS_TOTAL/TOTAL_ASSETS)*100,2) as Temporary_Assets_Divided_Total_Assets,\r\n"
	 		+ "Round((TEMPORART_ASSETS_TOTAL/VOLATILE_LIAB_UPTO_1_YR_TOTAL)*100,2) as Temporary_Assets_Divided_Volatile_Liab,\r\n"
	 		+ "Round((VOLATILE_LIAB_UPTO_1_YR_TOTAL/TOTAL_ASSETS)*100,2) Volatile_Liab_Divided_Total_Assets,\r\n"
	 		+ "TOTAL_ADVANCES, FIXED_ASSETS,Loans_Mandatory_SLR_Mandatory_CRR_Fixed_assets\r\n"
	 		+ "FROM (SELECT CASH, BALANCE_WITH_BANKS, BP_BD_UPTO_1_YEAR, INVEST_UPTO_1_YEAR, SWAP_FUND_UPTO_1_YEAR_ASSET,\r\n"
	 		+ "(CASH+ BALANCE_WITH_BANKS+ BP_BD_UPTO_1_YEAR+ INVEST_UPTO_1_YEAR+ SWAP_FUND_UPTO_1_YEAR_ASSET) AS Temporart_Assets_Total,\r\n"
	 		+ "CRR, BALANCE_CURRENT_ACC_OTHER_BANKS, OTHER_ASSETS,(CRR+ BALANCE_CURRENT_ACC_OTHER_BANKS+ OTHER_ASSETS) As Earning_Assets_Total,TOTAL_ASSETS,\r\n"
	 		+ "TOTAL_ASSETS - (CRR+ BALANCE_CURRENT_ACC_OTHER_BANKS+ OTHER_ASSETS) as Net_of_Earning_Assets_Total,\r\n"
	 		+ "INTERBANK, CASA, TERM_DEPOSIT, NETWORTH,(INTERBANK+ CASA+ TERM_DEPOSIT+ NETWORTH) As CASA_ABV_1_YR_TOTAL,\r\n"
	 		+ "TD_UPTO_1_YEAR, DEPOSIT_INTERBANK_CASA, BORROWINGS, LC_FULL, SWAP_FUND_UPTO_1_YEAR_LIAB,\r\n"
	 		+ "(TD_UPTO_1_YEAR+DEPOSIT_INTERBANK_CASA+ BORROWINGS+ LC_FULL+ SWAP_FUND_UPTO_1_YEAR_LIAB ) as Volatile_Liab_upto_1_YR_TOTAL,\r\n"
	 		+ "TOTAL_ADVANCES, FIXED_ASSETS,Loans_Mandatory_SLR_Mandatory_CRR_Fixed_assets FROM (Select R47_TOTAL AS Cash,R48_TOTAL+R49_TOTAL AS Balance_with_banks,\r\n"
	 		+ "(R54_DAY1+ R54_DAY2_7+ R54_DAY8_14+ R54_DAY15_30+ R54_DAY31_TO_2M+ R54_MORE2M_TO_3M+ R54_OVER3M_TO_6M+ R54_OVER6M_TO_1Y) BP_BD_UPTO_1_YEAR,\r\n"
	 		+ "(R52_DAY1+ R52_DAY2_7+ R52_DAY8_14+ R52_DAY15_30+ R52_DAY31_TO_2M+ R52_MORE2M_TO_3M+ R52_OVER3M_TO_6M+ R52_OVER6M_TO_1Y) INVEST_UPTO_1_YEAR,\r\n"
	 		+ "(R63_DAY1+ R63_DAY2_7+ R63_DAY8_14+ R63_DAY15_30+ R63_DAY31_TO_2M+ R63_MORE2M_TO_3M+ R63_OVER3M_TO_6M+ R63_OVER6M_TO_1Y) SWAP_FUND_UPTO_1_YEAR_ASSET,\r\n"
	 		+ "R48_TOTAL AS CRR,R50_TOTAL Balance_current_acc_other_banks,R59_TOTAL AS OTHER_ASSETS,R70_TOTAL AS TOTAL_ASSETS,\r\n"
	 		+ "R20_OVER1Y_TO_3Y+ R20_OVER3Y_TO_5Y+ R20_OVER5Y+R38_OVER1Y_TO_3Y+ R38_OVER3Y_TO_5Y+ R38_OVER5Y AS Interbank,\r\n"
	 		+ "R14_OVER1Y_TO_3Y+ R14_OVER3Y_TO_5Y+ R14_OVER5Y+R15_OVER1Y_TO_3Y+ R15_OVER3Y_TO_5Y+ R15_OVER5Y AS CASA,\r\n"
	 		+ "R16_OVER1Y_TO_3Y+ R16_OVER3Y_TO_5Y+ R16_OVER5Y AS Term_Deposit,R11_OVER5Y+R12_OVER5Y AS NETWORTH,\r\n"
	 		+ "(R16_DAY1+ R16_DAY2_7+ R16_DAY8_14+ R16_DAY15_30+ R16_DAY31_TO_2M+ R16_MORE2M_TO_3M+ R16_OVER3M_TO_6M+ R16_OVER6M_TO_1Y) TD_UPTO_1_YEAR,\r\n"
	 		+ "((R14_DAY1+ R14_DAY2_7+ R14_DAY8_14+ R14_DAY15_30+ R14_DAY31_TO_2M+ R14_MORE2M_TO_3M+ R14_OVER3M_TO_6M+ R14_OVER6M_TO_1Y)+\r\n"
	 		+ "(R15_DAY1+ R15_DAY2_7+ R15_DAY8_14+ R15_DAY15_30+ R15_DAY31_TO_2M+ R15_MORE2M_TO_3M+ R15_OVER3M_TO_6M+ R15_OVER6M_TO_1Y)) AS Deposit_Interbank_CASA,\r\n"
	 		+ "(R20_DAY1+ R20_DAY2_7+ R20_DAY8_14+ R20_DAY15_30+ R20_DAY31_TO_2M+ R20_MORE2M_TO_3M+ R20_OVER3M_TO_6M+ R20_OVER6M_TO_1Y) Borrowings,R32_TOTAL AS LC_FULL,\r\n"
	 		+ "(R35_DAY1+ R35_DAY2_7+ R35_DAY8_14+ R35_DAY15_30+ R35_DAY31_TO_2M+ R35_MORE2M_TO_3M+ R35_OVER3M_TO_6M+ R35_OVER6M_TO_1Y) SWAP_FUND_UPTO_1_YEAR_LIAB,\r\n"
	 		+ "(R53_TOTAL+R57_TOTAL) As Total_Advances, R58_TOTAL As Fixed_assets,(R48_TOTAL+R53_TOTAL+R57_TOTAL) As Loans_Mandatory_SLR_Mandatory_CRR_Fixed_assets\r\n"
	 		+ "from RT_SLS_USD Where REPORT_DATE = ?1 AND REPORT_CURRENCY = 'All_currency_converted_into_AED')))", nativeQuery = true)
	 List<Object[]> GetStockapproachratio(Date Selecteddate);
	 
	 
	 ///Get Ratio From the Matrix Monitor Table
	 @Query(value="select TO_CHAR(REPORT_DATE,'DD-MM-YYYY') AS REPORT_DATE,VOLATILE_LIAB_TEMP_ASSETS_DIVIDED_EARNING_ASSETS_TEMP_ASSETS, CORE_DEPOSIT_DIVIDED_TOTAL_ASSETS,\r\n"
	 		+ "ADV_CRR_FIXED_ASSET_DIVI_TOTAL_ASSET, ADV_CRR_FIXED_ASSET_DIVI_CORE_DEPO, TEMPORARY_ASSETS_DIVIDED_TOTAL_ASSETS,\r\n"
	 		+ "TEMPORARY_ASSETS_DIVIDED_VOLATILE_LIAB, VOLATILE_LIAB_DIVIDED_TOTAL_ASSETS from(\r\n"
	 		+ "SELECT REPORT_DATE,VOLATILE_LIAB_UPTO_1_YR_TOTAL,TEMPORART_ASSETS_TOTAL,EARNING_ASSETS_TOTAL,CASA_ABV_1_YR_TOTAL,TOTAL_ASSETS,\r\n"
	 		+ "Loans_Mandatory_SLR_Mandatory_CRR_Fixed_assets,VOLATILE_LIAB_TEMP_ASSETS_DIVIDED_EARNING_ASSETS_TEMP_ASSETS,\r\n"
	 		+ "CORE_DEPOSIT_DIVIDED_TOTAL_ASSETS, ADV_CRR_FIXED_ASSET_DIVI_TOTAL_ASSET, ADV_CRR_FIXED_ASSET_DIVI_CORE_DEPO,\r\n"
	 		+ "TEMPORARY_ASSETS_DIVIDED_TOTAL_ASSETS, TEMPORARY_ASSETS_DIVIDED_VOLATILE_LIAB, VOLATILE_LIAB_DIVIDED_TOTAL_ASSETS from(\r\n"
	 		+ "SELECT REPORT_DATE,CASH, BALANCE_WITH_BANKS, BP_BD_UPTO_1_YEAR, INVEST_UPTO_1_YEAR, SWAP_FUND_UPTO_1_YEAR_ASSET,\r\n"
	 		+ "TEMPORART_ASSETS_TOTAL,(TEMPORART_ASSETS_TOTAL - SWAP_FUND_UPTO_1_YEAR_ASSET) AS STOCK_TEMPORART_ASSETS_TOTAL_WITHOUT_SWAP\r\n"
	 		+ ", CRR, BALANCE_CURRENT_ACC_OTHER_BANKS, OTHER_ASSETS, EARNING_ASSETS_TOTAL,\r\n"
	 		+ "TOTAL_ASSETS, NET_OF_EARNING_ASSETS_TOTAL, INTERBANK, CASA, TERM_DEPOSIT, NETWORTH, CASA_ABV_1_YR_TOTAL,\r\n"
	 		+ "TD_UPTO_1_YEAR, DEPOSIT_INTERBANK_CASA, BORROWINGS, LC_FULL, SWAP_FUND_UPTO_1_YEAR_LIAB, VOLATILE_LIAB_UPTO_1_YR_TOTAL,\r\n"
	 		+ "(VOLATILE_LIAB_UPTO_1_YR_TOTAL-SWAP_FUND_UPTO_1_YEAR_LIAB) STOCK_VOLATILE_LIAB_TOTAL_WITHOUT_SWAP,\r\n"
	 		+ "Round(((VOLATILE_LIAB_UPTO_1_YR_TOTAL - TEMPORART_ASSETS_TOTAL)/\r\n"
	 		+ "(NET_OF_EARNING_ASSETS_TOTAL - TEMPORART_ASSETS_TOTAL))*100,2) AS Volatile_Liab_Temp_Assets_divided_Earning_Assets_Temp_Assets,\r\n"
	 		+ "Round((CASA_ABV_1_YR_TOTAL/TOTAL_ASSETS)*100,2) As Core_Deposit_divided_Total_Assets,\r\n"
	 		+ "Round(((TOTAL_ADVANCES+ FIXED_ASSETS+CRR)/TOTAL_ASSETS)*100,2) As Adv_CRR_Fixed_asset_divi_Total_asset,\r\n"
	 		+ "Round(((TOTAL_ADVANCES+ FIXED_ASSETS+CRR)/CASA_ABV_1_YR_TOTAL)*100,2) As Adv_CRR_Fixed_asset_divi_Core_Depo,\r\n"
	 		+ "Round((TEMPORART_ASSETS_TOTAL/TOTAL_ASSETS)*100,2) as Temporary_Assets_Divided_Total_Assets,\r\n"
	 		+ "Round((TEMPORART_ASSETS_TOTAL/VOLATILE_LIAB_UPTO_1_YR_TOTAL)*100,2) as Temporary_Assets_Divided_Volatile_Liab,\r\n"
	 		+ "Round((VOLATILE_LIAB_UPTO_1_YR_TOTAL/TOTAL_ASSETS)*100,2) Volatile_Liab_Divided_Total_Assets,\r\n"
	 		+ "TOTAL_ADVANCES, FIXED_ASSETS,Loans_Mandatory_SLR_Mandatory_CRR_Fixed_assets\r\n"
	 		+ "FROM (SELECT REPORT_DATE,CASH, BALANCE_WITH_BANKS, BP_BD_UPTO_1_YEAR, INVEST_UPTO_1_YEAR, SWAP_FUND_UPTO_1_YEAR_ASSET,\r\n"
	 		+ "(CASH+ BALANCE_WITH_BANKS+ BP_BD_UPTO_1_YEAR+ INVEST_UPTO_1_YEAR+ SWAP_FUND_UPTO_1_YEAR_ASSET) AS Temporart_Assets_Total,\r\n"
	 		+ "CRR, BALANCE_CURRENT_ACC_OTHER_BANKS, OTHER_ASSETS,(CRR+ BALANCE_CURRENT_ACC_OTHER_BANKS+ OTHER_ASSETS) As Earning_Assets_Total,TOTAL_ASSETS,\r\n"
	 		+ "TOTAL_ASSETS - (CRR+ BALANCE_CURRENT_ACC_OTHER_BANKS+ OTHER_ASSETS) as Net_of_Earning_Assets_Total,\r\n"
	 		+ "INTERBANK, CASA, TERM_DEPOSIT, NETWORTH,(INTERBANK+ CASA+ TERM_DEPOSIT+ NETWORTH) As CASA_ABV_1_YR_TOTAL,\r\n"
	 		+ "TD_UPTO_1_YEAR, DEPOSIT_INTERBANK_CASA, BORROWINGS, LC_FULL, SWAP_FUND_UPTO_1_YEAR_LIAB,\r\n"
	 		+ "(TD_UPTO_1_YEAR+DEPOSIT_INTERBANK_CASA+ BORROWINGS+ LC_FULL+ SWAP_FUND_UPTO_1_YEAR_LIAB ) as Volatile_Liab_upto_1_YR_TOTAL,\r\n"
	 		+ "TOTAL_ADVANCES, FIXED_ASSETS,Loans_Mandatory_SLR_Mandatory_CRR_Fixed_assets FROM (Select REPORT_DATE,R47_TOTAL AS Cash,R48_TOTAL+R49_TOTAL AS Balance_with_banks,\r\n"
	 		+ "(R54_DAY1+ R54_DAY2_7+ R54_DAY8_14+ R54_DAY15_30+ R54_DAY31_TO_2M+ R54_MORE2M_TO_3M+ R54_OVER3M_TO_6M+ R54_OVER6M_TO_1Y) BP_BD_UPTO_1_YEAR,\r\n"
	 		+ "(R52_DAY1+ R52_DAY2_7+ R52_DAY8_14+ R52_DAY15_30+ R52_DAY31_TO_2M+ R52_MORE2M_TO_3M+ R52_OVER3M_TO_6M+ R52_OVER6M_TO_1Y) INVEST_UPTO_1_YEAR,\r\n"
	 		+ "(R63_DAY1+ R63_DAY2_7+ R63_DAY8_14+ R63_DAY15_30+ R63_DAY31_TO_2M+ R63_MORE2M_TO_3M+ R63_OVER3M_TO_6M+ R63_OVER6M_TO_1Y) SWAP_FUND_UPTO_1_YEAR_ASSET,\r\n"
	 		+ "R48_TOTAL AS CRR,R50_TOTAL Balance_current_acc_other_banks,R59_TOTAL AS OTHER_ASSETS,R70_TOTAL AS TOTAL_ASSETS,\r\n"
	 		+ "R20_OVER1Y_TO_3Y+ R20_OVER3Y_TO_5Y+ R20_OVER5Y+R38_OVER1Y_TO_3Y+ R38_OVER3Y_TO_5Y+ R38_OVER5Y AS Interbank,\r\n"
	 		+ "R14_OVER1Y_TO_3Y+ R14_OVER3Y_TO_5Y+ R14_OVER5Y+R15_OVER1Y_TO_3Y+ R15_OVER3Y_TO_5Y+ R15_OVER5Y AS CASA,\r\n"
	 		+ "R16_OVER1Y_TO_3Y+ R16_OVER3Y_TO_5Y+ R16_OVER5Y AS Term_Deposit,R11_OVER5Y+R12_OVER5Y AS NETWORTH,\r\n"
	 		+ "(R16_DAY1+ R16_DAY2_7+ R16_DAY8_14+ R16_DAY15_30+ R16_DAY31_TO_2M+ R16_MORE2M_TO_3M+ R16_OVER3M_TO_6M+ R16_OVER6M_TO_1Y) TD_UPTO_1_YEAR,\r\n"
	 		+ "((R14_DAY1+ R14_DAY2_7+ R14_DAY8_14+ R14_DAY15_30+ R14_DAY31_TO_2M+ R14_MORE2M_TO_3M+ R14_OVER3M_TO_6M+ R14_OVER6M_TO_1Y)+\r\n"
	 		+ "(R15_DAY1+ R15_DAY2_7+ R15_DAY8_14+ R15_DAY15_30+ R15_DAY31_TO_2M+ R15_MORE2M_TO_3M+ R15_OVER3M_TO_6M+ R15_OVER6M_TO_1Y)) AS Deposit_Interbank_CASA,\r\n"
	 		+ "(R20_DAY1+ R20_DAY2_7+ R20_DAY8_14+ R20_DAY15_30+ R20_DAY31_TO_2M+ R20_MORE2M_TO_3M+ R20_OVER3M_TO_6M+ R20_OVER6M_TO_1Y) Borrowings,R32_TOTAL AS LC_FULL,\r\n"
	 		+ "(R35_DAY1+ R35_DAY2_7+ R35_DAY8_14+ R35_DAY15_30+ R35_DAY31_TO_2M+ R35_MORE2M_TO_3M+ R35_OVER3M_TO_6M+ R35_OVER6M_TO_1Y) SWAP_FUND_UPTO_1_YEAR_LIAB,\r\n"
	 		+ "(R53_TOTAL+R57_TOTAL) As Total_Advances, R58_TOTAL As Fixed_assets,(R48_TOTAL+R53_TOTAL+R57_TOTAL) As Loans_Mandatory_SLR_Mandatory_CRR_Fixed_assets\r\n"
	 		+ "from RT_SLS_USD Where REPORT_CURRENCY = 'All_currency_converted_into_AED' AND REPORT_DATE IN (\r\n"
	 		+ "SELECT LAST_DAY(ADD_MONTHS(TRUNC(?1, 'YEAR'), LEVEL - 1))AS month_end FROM dual CONNECT BY LEVEL <= 12 ))))Order by REPORT_DATE Asc)",nativeQuery=true)
		List<Object[]> GetStockapproachratioGraph(Date Selecteddate);
	 
}
