
package com.bornfire.xbrl.entities;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import java.math.BigDecimal;

@Repository
public interface RT_TreasuryCreditRepo extends JpaRepository<RT_TreasuryCreditEntity, BigDecimal> {
	// Add custom queries if needed

	@Query(value = "select * from BCBUAE_TREASURY_CRE_LMT_MANAGEMENT where DEL_FLG != 'Y'", nativeQuery = true)
	List<RT_TreasuryCreditEntity> getTClist();

	@Query(value = "SELECT REPORT_DATE, BANK_NAME, HEAD_OFFICE_SUBSIDIARY, SUBSIDIARY, BANK_SYMBOL, CONVENTIONAL_ISLAMIC, LOCAL_FOREIGN, CBUAE_TIERING, COUNTERPARTY_NAME, COUNTERPARTY_INT_REF, COUNTERPARTY_RISK_RATING, FINAL_RATING_CBUAE, COUNTRY_OF_RISK, CBUAE_GEOGRAPHICAL_ZONE, COUNTERPARTY_TYPE, LIMIT_AED_MONEYMARKET, UTILIZATION_AED_MONEYMARKET, MONEYMARKET_PERCENT, LIMIT_AED_REPO, UTILIZATION_AED_REPO, REPO_PERCENT, LIMIT_AED_BONDS, UTILIZATION_AED_BONDS, BONDS_PERCENT, LIMIT_AED_EQUITY, UTILIZATION_AED_EQUITY, EQUITY_PERCENT, LIMIT_AED_CREDIT, UTILIZATION_AED_CREDIT, CREDIT_PERCENT, LIMIT_AED_OTHER, UTILIZATION_AED_OTHER, OTHER_PERCENT, LIMIT_AED_NOSTRO, UTILIZATION_AED_NOSTRO, NOSTRO_PERCENT, LIMIT_AED_DERIVATIVES, UTILIZATION_AED_DERIVATIVES, DERIVATIVES_PERCENT, LIMIT_AED_FXSETTLEMENT, UTILIZATION_AED_FXSETTLEMENT, FXSETTLEMENT_PERCENT, LIMIT_AED_BONDSETTLEMENT, UTILIZATION_AED_BONDSETTLEMENT, BONDSETTLEMENT_PERCENT, TREASURY_LMT_AED, TREASURY_LMT, EXPOSURE_AED, EXPOSURE FROM BCBUAE_TREASURY_CRE_LMT_MANAGEMENT", nativeQuery = true)
	List<Object[]> getTreasuryData();

}
