-- Add new rate columns for CBUAE MM Data new template
ALTER TABLE BCBUAE_MM_DATA ADD (
	FIXED_RATE            VARCHAR2(100 BYTE),
	FLOATING_RATE         VARCHAR2(100 BYTE),
	FLOATING_RATE_BASIS   VARCHAR2(100 BYTE)
);

COMMENT ON COLUMN BCBUAE_MM_DATA.FIXED_RATE IS 'Fixed Rate (%)';
COMMENT ON COLUMN BCBUAE_MM_DATA.FLOATING_RATE IS 'Floating Rate Type';
COMMENT ON COLUMN BCBUAE_MM_DATA.FLOATING_RATE_BASIS IS 'Interest/Profit rate Margin (Only in case of Floating Rate)';
COMMENT ON COLUMN BCBUAE_MM_DATA.INTEREST_PROFIT_RATE IS 'Interest/Profit Rate Type';
