-- Upload monitor delete request / approval workflow columns
ALTER TABLE BCBUAERT_UPLOAD_MONITOR ADD (
    DELETE_REQUEST_STATUS  VARCHAR2(20),
    DELETE_REMARKS         VARCHAR2(1000),
    DELETE_REQUESTED_BY    VARCHAR2(100),
    DELETE_REQUESTED_AT    TIMESTAMP,
    DELETE_APPROVED_BY     VARCHAR2(100),
    DELETE_APPROVED_AT     TIMESTAMP
);

-- Optional: allow DELETED in UPLOAD_STATUS if you prefer that column to reflect deletion
-- ALTER TABLE BCBUAERT_UPLOAD_MONITOR DROP CONSTRAINT CK_BCBUAERT_UPMON_STATUS;
-- ALTER TABLE BCBUAERT_UPLOAD_MONITOR ADD CONSTRAINT CK_BCBUAERT_UPMON_STATUS
--     CHECK (UPLOAD_STATUS IN ('IN_PROGRESS', 'SUCCESS', 'FAILED', 'REPLACED', 'DELETED'));
