-- Maps bill/upload bank names to authorized counterparty bank names (maintained on bill edit).
CREATE SEQUENCE MIS_ASL_EXP_BANK_MAP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE MIS_ASL_EXPOSURE_BANK_NAME_MAP (
    ID              NUMBER(19)       NOT NULL,
    OLD_BANK_NAME   VARCHAR2(500)    NOT NULL,
    NEW_BANK_NAME   VARCHAR2(500)    NOT NULL,
    BILL_SRL_NO     VARCHAR2(50),
    CREATE_USER     VARCHAR2(100),
    CREATE_TIME     TIMESTAMP,
    MODIFY_USER     VARCHAR2(100),
    MODIFY_TIME     TIMESTAMP,
    DEL_FLG         CHAR(1)          DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_MIS_ASL_EXP_BANK_MAP PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_MIS_ASL_EXP_BANK_MAP_OLD ON MIS_ASL_EXPOSURE_BANK_NAME_MAP (
    UPPER(TRIM(OLD_BANK_NAME))
);

COMMENT ON TABLE MIS_ASL_EXPOSURE_BANK_NAME_MAP IS 'ASL exposure bill bank name alias map (source name to authorized counterparty name)';
