-- =============================================================================
-- RT_ANALYTICAL_PIVOT_LAYOUT - stores saved pivot layouts per user
-- =============================================================================

CREATE SEQUENCE RT_ANALYTICAL_PIVOT_LAYOUT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE RT_ANALYTICAL_PIVOT_LAYOUT (
    LAYOUT_ID          NUMBER(19)      NOT NULL,
    USER_ID            VARCHAR2(100)   NOT NULL,
    LAYOUT_NAME        VARCHAR2(120)   NOT NULL,
    TABLE_NAME         VARCHAR2(100)   NOT NULL,
    ROW_COLUMNS        VARCHAR2(4000),
    COLUMN_COLUMNS     VARCHAR2(4000),
    AGGREGATION_TYPE   VARCHAR2(10)    NOT NULL,
    VALUE_COLUMN       VARCHAR2(100),
    AGGREGATE_TRANSFORM  VARCHAR2(20),
    AGGREGATE_OPERAND    VARCHAR2(50),
    CREATED_TIME       TIMESTAMP(6),
    UPDATED_TIME       TIMESTAMP(6),
    CONSTRAINT PK_RT_ANALYTICAL_PIVOT_LAYOUT PRIMARY KEY (LAYOUT_ID),
    CONSTRAINT UK_RT_ANALYTICAL_LAYOUT UNIQUE (USER_ID, LAYOUT_NAME),
    CONSTRAINT CHK_RT_ANALYTICAL_AGG CHECK (AGGREGATION_TYPE IN ('SUM', 'COUNT'))
);

CREATE INDEX IDX_RT_ANALYTICAL_USER ON RT_ANALYTICAL_PIVOT_LAYOUT (USER_ID, UPDATED_TIME);

