-- Widen dimension JSON storage for filters (optional; run if table already exists with VARCHAR2(1000))
ALTER TABLE RT_ANALYTICAL_PIVOT_LAYOUT MODIFY ( ROW_COLUMNS VARCHAR2(4000) );
ALTER TABLE RT_ANALYTICAL_PIVOT_LAYOUT MODIFY ( COLUMN_COLUMNS VARCHAR2(4000) );
