-- Step definitions per report (procedure name for CallableStatement)
-- Run after RT_REPORT_MASTER exists.

CREATE SEQUENCE RT_REPORT_STEP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE RT_REPORT_STEP (
    STEP_ID          NUMBER(19)     NOT NULL,
    REPORT_ID        NUMBER(19)     NOT NULL,
    STEP_ORDER       NUMBER(10)     NOT NULL,
    PROCEDURE_NAME   VARCHAR2(200)  NOT NULL,
    CONSTRAINT PK_RT_REPORT_STEP PRIMARY KEY (STEP_ID),
    CONSTRAINT UK_RT_REP_STEP_ORD UNIQUE (REPORT_ID, STEP_ORDER)
);

CREATE INDEX IDX_RT_STEP_REP ON RT_REPORT_STEP (REPORT_ID);

COMMENT ON TABLE RT_REPORT_STEP IS 'Ordered procedures for a report; STEP_ID is used in run API';
