-- Per-step execution status for a report calendar day (aligned with Report Control Center date filter)
-- Run after RT_REPORT_STEP exists.

CREATE SEQUENCE RT_REPORT_STEP_EXEC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE RT_REPORT_STEP_EXEC (
    ID               NUMBER(19)     NOT NULL,
    REPORT_ID        NUMBER(19)     NOT NULL,
    STEP_ID          NUMBER(19)     NOT NULL,
    REPORT_DATE      DATE           NOT NULL,
    STATUS           VARCHAR2(20)   NOT NULL,
    ERROR_MESSAGE    VARCHAR2(4000),
    EXEC_USER_NAME   VARCHAR2(200),
    STEP_START_TIME  TIMESTAMP(6),
    STEP_END_TIME    TIMESTAMP(6),
    CONSTRAINT PK_RT_REPORT_STEP_EXEC PRIMARY KEY (ID),
    CONSTRAINT UK_RT_STEP_EXEC_DAY UNIQUE (REPORT_ID, STEP_ID, REPORT_DATE)
);

CREATE INDEX IDX_RT_STEP_EXEC_REP_DT ON RT_REPORT_STEP_EXEC (REPORT_ID, REPORT_DATE);

COMMENT ON COLUMN RT_REPORT_STEP_EXEC.STATUS IS 'SUCCESS, FAILED, or PENDING';
COMMENT ON COLUMN RT_REPORT_STEP_EXEC.EXEC_USER_NAME IS 'Session user who ran the step (e.g. USERID)';
COMMENT ON COLUMN RT_REPORT_STEP_EXEC.STEP_START_TIME IS 'When the step run began';
COMMENT ON COLUMN RT_REPORT_STEP_EXEC.STEP_END_TIME IS 'When the step run finished (success or failure)';